### ISSUE TITLE
Doesn't work :(

### ISSUE THREAD

**Issue by hamcoremusic** [Xetera/fixtiktok#1]
Looks like this might not be working anymore. Tried in DMs and on a public server!

**Comment by Xetera** [comment]
Yeahh tiktok seems to really not like bots. I'll have to take another look at this over the weekend when I'm free :disappointed:

**Comment by Xetera** [comment]
Should be working again. Looks like tiktok is load balancing between a backend that runs on nextjs and https://github.com/sigi-framework/sigi so requests that go to the wrong backend randomly fail if not dealt with properly lol

**Comment by hamcoremusic** [comment]
Awesome! Does this by chance work with the share links that have the subdomain `vm.` in front of them? 

For example `https://vm.tiktok.com/ZMLRMM4KU/`?

**Comment by hamcoremusic** [comment]
Nevermind it does when you put `https://vm.fixtiktok.com`! This is awesome!

**Comment by inxomnyaa** [comment]
> Nevermind it does when you put `https://vm.fixtiktok.com`! This is awesome!

this appears top be broken now

https://vm.tiktok.com/ZMYD2yJvK/
https://vm.fixtiktok.com/ZMYD2yJvK/
![image](https://user-images.githubusercontent.com/8733998/221378186-94167a20-6e06-4235-86ae-80b4539aaa25.png)

**Comment by Xetera** [comment]
Part of this problem is Tiktok's video links don't end with an `mp4` and that seems to be a criteria for Discord to embed videos in opengraph tags. I solved that by doing an internal redirect from an `mp4` fixtiktok link to tiktok's regular video link and that worked for a while. But it seems discord changed how their redirects coming from opengraph endpoints are followed and it stopped working some time ago and I haven't been able to get it working since. 

I can try taking a second look but I doubt they've changed that behavior. This could be fixed by directly streaming the video from the fixtiktok link but I'm not really interested in that since it would be very costly.

**Comment by inxomnyaa** [comment]
the domain just seems to be down, i am getting a 404

from the looks of the fxtwitter source code the .mp4 extension does not really look like a requirement
Streamable links don't have that either iirc

**Comment by Xetera** [comment]
Maybe they changed it. When I first made it the only way to get it to work was with a redirect. I'll take another look
